services:
  ollama:
    image: docker.io/ollama/ollama:latest
    restart: always
    ports:
      - "127.0.0.1:11434:11434"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama.rule=Host(`${OLLAMA_SUBDOMAIN:-ollama}.${DOMAIN_NAME}`)
      - traefik.http.routers.ollama.tls=true
      - traefik.http.routers.ollama.entrypoints=websecure
      - traefik.http.routers.ollama.tls.certresolver=${TRAEFIK_RESOLVER:-myresolver}
      - traefik.http.services.ollama.loadbalancer.server.port=11434
    environment:
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
